### ISSUE TITLE
Search an NPC by the name and class don’t accept spaces

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#10]
O.S | Windows 11
Browser | Mozilla Firefox 121.0.1 (64-bit)

**Description**
When search a NPC by name and class doesn't work when you use spaces as separators, only with the name and class all together, this can be confusing considering that the structure shown to the user not only uses a space as a separator but also parentheses.

**Steps**

1. Click the icon with 2 persons at the top right 
2. Click the search bar 
3. Write the name and the class of the NPC

**Expected Output**
A list of NPC with that name and class

**Real Output**

[AMT-S-4a.png](https://drive.google.com/file/d/1wZpdXAFEmeyLW614SnQUy3Mkm-WMNGqe/view?usp=drive_link)
[AMT-S-4b.png](https://drive.google.com/file/d/19kPkYsHf55HH1tSXs7ACsqm5CYu36HbW/view?usp=drive_link)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
