### ISSUE TITLE
Search an NPC by the class and name doesn’t show results

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#11]
O.S | Windows 11
Browser | Mozilla Firefox 121.0.1 (64-bit)

**Description**
When search a NPC by class and name doesn't show any result no matter if use or not any separator.

**Steps**
1. Click the icon with 2 persons at the top right
2. Click the search bar
3. Write the class and the name of the NPC

**Expected Output**
A list of NPC that match with the class and name

Real Output
[AMT-S-5a.png](https://drive.google.com/file/d/1jPtCV2Rvc-wuD3plg2jsci4DgJAZ9ZaO/view?usp=drive_link)

[AMT-S-5b.png](https://drive.google.com/file/d/10NjOkU5ysO2hcP2M86EE6HqNhG5yn1Ng/view?usp=drive_link)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
