### ISSUE TITLE
Search an NPC by the name and level doesn’t show results

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#12]
O.S | Windows 11
Browser | Mozilla Firefox 121.0.1 (64-bit)

**Description**
When search a NPC by the name and level doesn’t show results with and without separators

**Steps**

1. Click the icon with 2 persons at the top right
2. Click the search bar
3. Write the name and the level of the NPC

**Expected Output**
A list of NPC with that name and level

**Real Output**
[AMT-S-6a.png](https://drive.google.com/file/d/1qb3tNC0vzZHb4LHpJMPUxJkAnyZs81_K/view?usp=drive_link)
[AMT-S-6c.png](https://drive.google.com/file/d/1Ojo1B_FytgiBo4DyuKDfTLiJzSHyj2qg/view?usp=drive_link)
[AMT-S-6b.png](https://drive.google.com/file/d/1zWzwp2-JhZMgfN_HF8csAsYOKRoZNVCw/view?usp=drive_link)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
