### ISSUE TITLE
Search by the NPC level and name  doesn’t show results

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#13]
O.S | Windows 11
Browser | Mozilla Firefox 121.0.1 (64-bit)

**Description**
Search an NPC by the level and name doesn’t show results with and without separators

**Steps**

1. Click the icon with 2 persons at the top right
2. Click the search bar
3. Write the level and the name of the NPC

**Expected Output**
A list of NPC with that level and name

**Real Output**
[AMT-S-7a.png](https://drive.google.com/file/d/1tfvrRQIwJg9_OSU-eJfOv2NmkPzftoWU/view?usp=drive_link)
[AMT-S-7b.png](https://drive.google.com/file/d/1inSrLY8jpo_gOcn7BMfhNKRRUZ_zwIdi/view?usp=drive_link)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
