### ISSUE TITLE
Search by the NPC level and class doesn’t show results

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#14]
O.S | Windows 11
Browser | Mozilla Firefox 121.0.1 (64-bit)

**Description**
Search by the NPC level and class doesn’t show results

**Steps**

1. Click the icon with 2 persons at the top right
2. Click the search bar
3. Write the level and class of the NPC

**Expected Output**
A list of NPC with that level and class

**Real Output**
[AMT-S-8a.png](https://drive.google.com/file/d/1z15a_NViiaS9PxP3VmmFuTzz2FjwYj_N/view?usp=drive_link)
[AMT-S-8b.png](https://drive.google.com/file/d/1ayo3YOt_TtNohlZqnwcv-6CyIIsantuK/view?usp=drive_link)
[AMT-S-8c.png](https://drive.google.com/file/d/1eurA-ZduOgA2AhIumIk5JwjK3GbgUGHo/view?usp=drive_link)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
