### ISSUE TITLE
The numbering of the npc is mixed between NPC

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#15]
O.S | Windows 11
Browser | Mozilla Firefox 121.0.1 (64-bit)

**Description**
when adding multiple and different NPCs the numbering increments sequentially for all the NPC this should increment differentiated for the NPC's with the same name

**Steps**

Click in the icon with 2 persons at the top right
Click multiple times in the "+" icon at the top left of diferent NPC cards

**Expected Output**

- The selected characters should be added
- The name of the character should match with the name of the NPC selected + number and this should de incremental with each new NPC with the same name added

**Real Output**
[AMP-ANPC-2.png](https://drive.google.com/file/d/1aBz92gFnnNN6UY6bHOoYZKuTfxakDLG2/view?usp=drive_link)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
