### ISSUE TITLE
The Info modal doesn’t show completely

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#16]
O.S | Windows 11
Browser | Mozilla Firefox 121.0.1 (64-bit)
screen resolution | 1366 x 768

**Description**
The Info modal doesn’t show completely, you scroll the modal to the end it only shows a number of skills, with the PCs Vir and Jerico it only goes up to "confection", but if you zoom out can see more skills and other section like “Habilidades de ki”

**Steps**

1. Click the info button of any PC that’s already uploaded
2. scroll to the end of the modal and check the last field
3. In the browser menu look for the zoom option and zoom out
4. scroll to the end of the modal and check the last field

**Expected Output**

The scroll in the modal should goes to the end of the list

**Real Output**
[AMT-ET-1a.png](https://drive.google.com/file/d/1D-pxJom9dGkHRzYAsdiriD_1tF2QotuB/view?usp=drive_link)
[AMT-ET-1b.png](https://drive.google.com/file/d/1gI_ImJ3LR1ZTmPZXGBrj3j8jXbCZYFJZ/view?usp=drive_link)
[AMT-ET-1c.png](https://drive.google.com/file/d/1Gfd5L3fup74W3eH2qTsKdvFYyY-fPlA-/view?usp=drive_link)

**Comment by aoalejo** [comment]
review again please, i thing it's fixed now
