### ISSUE TITLE
the increment of consumables is not consistent

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#17]
O.S | Windows 11
Browser | Google Chrome121.0.6167.140 (Build oficial) (64 bits)

**Description**
When create a character with the “crear nuevo personaje” function, the increments of consumables like “Vida”, “Cansancio”, “Zeon”, “Ki” and “CV” take 10% of the max value of the consumable instead the value of 10 like when upload a character or add a NPC.

**Steps**

1. Click in the button "crear nuevo personaje" in the left panel in the superior mid
2. In the section "detalles" fill the fields “Vida”, “Cansancio”, “Zeon”, “Ki” or “CV”  with any value above 10 
3. Click the "guardar" button
4. Click the button “Atacar”, “Parada” or “Esquiva”

**Expected Output**

[ ] - The increments of the consumable should have the value of 10 

**Real Output**
[AMT-ET-DR-4.webm](https://drive.google.com/file/d/1k_sMzeh4hAi6Nu1NSeum2wsZYqxTLIDZ/view?usp=drive_link)

**Comment by aoalejo** [comment]
Is it better to have an increment fixed on 10 or a 10 percent increment? the percent increment is better when we don't know the value (or we don't want the user to input, like in the fast generation of characters) but with the sheet import, we have lots of data (like the ki values), what do you think?

**Comment by aoalejo** [comment]
maybe rounding on tens or fives is the best option
