### ISSUE TITLE
The "Nature" of the character is not taken into account when uploading one

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#18]
O.S | Windows 11
Browser | Mozilla Firefox 122.0 (64-bit)

**Description**
The field “natura” isn’t the same in the .json and the uploaded character, this take the default value of 5, eg. the file [Vir.json ](https://drive.google.com/file/d/1s3ewWBpuPV-cIMuP-hPJs7sQmri79RWk/view?usp=drive_link) has the field “natura” : 10 ,  once uploaded the value of the natura is 5.

**Steps**

1. Click the button "cargar personaje" in the upper side of the left panel
2. Select the file [Vir.json ](https://drive.google.com/file/d/1s3ewWBpuPV-cIMuP-hPJs7sQmri79RWk/view?usp=drive_link)and click in open
3. Click in the gear icon of the uploaded character
4. compare the “natura” value with the value of the .json

**Expected Output**
the character should have the same value in the “natura” field

**Real Output**
[AMT-ET-DR-5a.png](https://drive.google.com/file/d/1AjK6-R0mNSLYCQ1neKA1RzRnPKobR7kN/view?usp=drive_link)
[AMT-ET-DR-5b.png](https://drive.google.com/file/d/1awndq4CK84FNC89g7V-Sv8xm372WalKB/view?usp=drive_link)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
