### ISSUE TITLE
Rolls do not take into account the "natura" of the character

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#19]
O.S | Windows 11
Browser | Mozilla Firefox 122.0 (64-bit)

**Description**
When rolling initiative, attack or defense the crit is not correctly limited by nature, is taken one category upper

**Steps**

1. Add a character or NPC
2. Click in the gear icon of the character and change the “natura” to 4
3. Click the “iniciativa” button in the top left of the left panel
4. Check the initiative of the characters
5. Repeat until found a critical 

**Expected Output**
Critical rolls should not add more rolls

**Real Output**
[AMT-ET-DR-3a.png](https://drive.google.com/file/d/1ALRrzD9B08_rSZQcN-O7vRUPWPPdVSY-/view?usp=drive_link)
[AMT-ET-DR-3b.png](https://drive.google.com/file/d/1XjpYFcADQCcBgOd1Q4Gt0SkbOWFIIC2R/view?usp=drive_link)
[AMT-ET-DR-3c.png](https://drive.google.com/file/d/149B0VEv43yxUcEfUPVU5vWtGlKuKPTJP/view?usp=drive_link)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
