### ISSUE TITLE
the roll button on the defense card don’t work

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#21]
O.S | Windows 11
Browser | Google Chrome121.0.6167.140 (Build oficial) (64 bits)

**Description**
When click the roll button in the defense card without select a character doesn’t make the roll

**Steps**
Without select a character click the roll button in the defense card on the right panel

**Expected Output**
the field “tirada de ataque” should fill with a random number between 1-100 when click the roll button 

**Real Output**

[AMT-ET-DR-6/7.webm](https://drive.google.com/file/d/1VpzbHmVTNzTY-DxKVtOzQtZ1c75K4xjV/view?usp=drive_link)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
