### ISSUE TITLE
Can't close the combat cards because the character name length

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#22]
**O.S** | Windows 11
**Browser** | Google Chrome121.0.6167.140 (Build oficial) (64 bits)
**Screen Resolution**| 1366 x 768

**Description**
When you upload a character or create a character with a name longer than 34 characters this push the X button making unable to click

**Steps**

1. Click in the "Crear Nuevo Personaje" button
2. Fill the name field with more than 34 characters
3. Click in the "guardar" button
4. Select the character as attacker or deffender

**Expected Output**
The X button of the defense and attack card should be always clickable no matter the length of the character name

**Real Output**
![Captura de pantalla 2024-02-11 125157](https://github.com/aoalejo/animaMasterToolkit/assets/151423052/a195677d-5bf9-4ba2-8903-ca4fb1e85583)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
