### ISSUE TITLE
The "Ataque" field doesn't have a proper max limiter

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#23]
**O.S** | Windows 11
**Browser** | Google Chrome121.0.6167.140 (Build oficial) (64 bits)

**Description**
When you fill the field " ataque" with a number with 21 figures or greater the number in the header of the card change to scientific notation and after the 308 figures this become 0

**Steps**
1. Click the field "ataque" in the right panel in the card "Ataca"
2. Fill in the field with 21 or more figures other than 0

**Expected Output**
The value should be limited 3 figures value

**Real Output**
![Captura de pantalla 2024-02-11 161557](https://github.com/aoalejo/animaMasterToolkit/assets/151423052/2d6cde4f-695d-4460-a7cb-e79abbbac94f)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
