### ISSUE TITLE
The "tirada de ataque" field doesn't have a proper max limiter

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#24]
**O.S** | Windows 11
**Browser** | Google Chrome121.0.6167.140 (Build oficial) (64 bits)

**Description**
When you fill the field "tirada de ataque" with a number with 21 figures or greater the number in the header of the card change to scientific notation and after the 308 figures this become 0

**Steps**
1. Click the field "tirada de ataque" in the right panel in the card "Ataca"
2. Fill in the field with 21 or more figures other than 0

**Expected Output**
The value should be limited 3 figures value

**Real Output**
![Captura de pantalla 2024-02-11 153722](https://github.com/aoalejo/animaMasterToolkit/assets/151423052/43656382-5b18-4b5d-812d-3db6cf2f8640)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
