### ISSUE TITLE
 The "tirada de defensa" field doesn't have a proper max limiter 

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#25]
**O.S** | Windows 11
**Browser** | Google Chrome121.0.6167.140 (Build oficial) (64 bits)

**Description**
When you fill the field "Defensa" with a number with 21 figures or greater the number in the header of the card change to scientific notation and after the 308 figures this become 0

**Steps**

1. Click the field "tirada de defensa" in the right panel in the card "Parada"
2. Fill in the field with 21 or more figures other than 0

**Expected Output**
 The value should be limited 3 figures value

**Real Output**

![Captura de pantalla 2024-02-11 181122](https://github.com/aoalejo/animaMasterToolkit/assets/151423052/88268133-a332-47f4-8191-0f404f2dde17)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
