### ISSUE TITLE
Can't scroll in the modifiers section in attack card

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#27]
**O.S** | Windows 11
**Browser** | Google Chrome121.0.6167.140 (Build oficial) (64 bits)

**Description**
When you add multiple modifiers that overflow the modifier container you cannot see all the additions

**Steps**

1. Click the "situacionales" button in the Attack card
2. Click multiples modifiers more than 6, 18 in big screens 
3. Close the "Modificadores afectando al personaje" modal

**Expected Output**
Should appear a horizontal scroll bar when the modifiers overflow the container

**Real Output**
![Captura de pantalla 2024-02-11 181846](https://github.com/aoalejo/animaMasterToolkit/assets/151423052/3b3de3e8-46a9-422d-a683-a648bb3bb0ec)

![Captura de pantalla 2024-02-11 182500](https://github.com/aoalejo/animaMasterToolkit/assets/151423052/50f034a8-810b-4696-accc-cbb12354fa18)

**Comment by aoalejo** [comment]
fixed on https://github.com/aoalejo/animaMasterToolkit/pull/36
