### ISSUE TITLE
Can't scroll in the modifiers section in defense card

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#28]
**O.S** | Windows 11
**Browser** | Google Chrome121.0.6167.140 (Build oficial) (64 bits)
 **Screen Resolution** | 1366 x 768

**Description**
 When you add all the modifiers in the defense card can't see completely the last modifiers

**Steps**
1. Click the "situacionales" button in the defense card
2. Click all the modifiers 
3. Close the "Modificadores afectando al personaje" modal

**Expected Output**
 Should appear a horizontal scroll bar when the modifiers overflow the container

**Real Output**
![Captura de pantalla 2024-02-11 183946](https://github.com/aoalejo/animaMasterToolkit/assets/151423052/e0f63007-4c30-410b-991a-81a26cc167fd)

**Comment by aoalejo** [comment]
fixed on https://github.com/aoalejo/animaMasterToolkit/pull/36
