### ISSUE TITLE
The scroll in the consumible section doesn't work

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#29]
**O.S** | Windows 11
**Browser** | Google Chrome121.0.6167.140 (Build oficial) (64 bits)
**Screen Resolution** | 1366 x 768

**Description**
When you add multiples consumable cards to a character in the attack or defense card in the middle panel the scroll bar doesn't work making Inaccessible the consumables and the add consumables button

**Steps**

1. Select any character as a defender or attacker
2. Click the "añadir" button in the consumables section 
3. Click the save button
4. repeat multiple times until the consumables overflow the containter

**Expected Output**
When hold the scroll bar and slide should show the other consumables created

**Real Output**
![Captura de pantalla 2024-02-11 184638](https://github.com/aoalejo/animaMasterToolkit/assets/151423052/a33cc33e-c31d-4446-b501-f5394eedaae1)

**Comment by aoalejo** [comment]
fixed on https://github.com/aoalejo/animaMasterToolkit/pull/36
