### ISSUE TITLE
The consumible name overflow outside the container

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#30]
**O.S** | Windows 11
**Browser** | Google Chrome121.0.6167.140 (Build oficial) (64 bits)

**Description**
When create a consumable with a long name this stick out the consumible card

**Steps**

1. Select any character as a defender or attacker
2. Click the "añadir" button in the consumables section
3. Fill the name field with more than 18 characters
4. Click the save button

**Expected Output**
The name of the consumible should not stick out the card

**Real Output**

![Captura de pantalla 2024-02-11 190619](https://github.com/aoalejo/animaMasterToolkit/assets/151423052/ef1c79ab-824d-4a70-8ee6-bbd7239ee341)

![Captura de pantalla 2024-02-11 190635](https://github.com/aoalejo/animaMasterToolkit/assets/151423052/a1fa2466-48f8-42ed-a6eb-edf3ce9b0435)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
