### ISSUE TITLE
The position of the delete button in the consumable card change position

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#31]
**O.S** | Windows 11
**Browser** | Google Chrome121.0.6167.140 (Build oficial) (64 bits)

**Description**
The position of the delete button in the consumable card change position when the increment is not setted or setted as 0

**Steps**

1. Select any character as a defender or attacker
2. Click the "añadir" button in the consumables section
3. Fill the field name with any name
4. Erase or fill with 0 the field "incremento"
5. Click the save button

**Expected Output**
The delete button should maintain the position no matter the name of the consumible

**Real Output**
![Captura de pantalla 2024-02-11 193329](https://github.com/aoalejo/animaMasterToolkit/assets/151423052/b9e6b6fb-198a-4748-88ee-bd184eb12093)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
