### ISSUE TITLE
Create a character doesn't have minimum limiter for the Life Points

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#5]
**O.S** | Windows 11
**Browser** | Google Chrome 121.0.6167.86 (Build oficial) (64 bits)

**Description**
When creating a character with the character creator, the life points field “Vida” doesn’t limit the minimum value, according with the core exxet P16 “Tabla 16: puntos de vida base” this should be at least 20

**steps**

1. Click in the button "crear nuevo personaje" in the left panel in the superior mid
2. In the section "detalles" fill the field "vida" with a value below the minimum
3. Click the "guardar" button

**Expected Output**

- Successfully add the character to the characters list
- The maximum value of field "vida" should be at least 20

**Real Output**
[AMT-CNC-3.webm](https://drive.google.com/file/d/1WUxK_M8lyHml6QR_MovMiPhuuKYY9w9Z/view?usp=drive_link)

**Comment by aoalejo** [comment]
it's limited now to 9999, I know it's not the expected answer, but I prefer not to limit more the creation, because it can be a monster or anything that has 100 points of fatigue per example.
