### ISSUE TITLE
Create a character doesn't have maximum limiter for the Life Points

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#6]
O.S | Windows 11
Browser | Google Chrome 121.0.6167.86 (Build oficial) (64 bits)

**Description**
When creating a character with the character creator, the life points field “Vida” doesn’t limit the maximum value, the maximum value is 5665, This is calculated taking into account
the core exxet P16 “Tabla 16: puntos de vida base” at constitution 20, the class “Maestro de armas” the core exxet P39 who have a life multiplier of 10 and the PD of a character lvl 20 the core exxet P25 “tabla 6: progresión por nivel” investing all the point in life points.

**steps**

1. Click in the button "crear nuevo personaje" in the left panel in the superior mid
2. In the section "detalles" fill the field "vida" with a value above the maximum
3. Click the "guardar" button

**Expected Output**

- Successfully add the character to the characters list
- The maximum value of field "vida" should be limited to 5665

Real Output
[AMT-CNC-4.png](https://drive.google.com/file/d/1h9v1NM7yJ_37s660d5BtmPHEhCmycvky/view?usp=drive_link)

**Comment by aoalejo** [comment]
it's limited now to 9999, I know it's not the expected answer, but I prefer not to limit more the creation, because it can be a monster or anything that has 100 points of fatigue per example.
