### ISSUE TITLE
Create a character doesn't have maximum limiter for the max fatigue points

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#8]
O.S | Windows 11
Browser | Google Chrome 121.0.6167.86 (Build oficial) (64 bits)

**Description**
When creating a character with the character creator, the fatigue field “cansancio” doesn’t limit the maximum value, according with the core exxet P12 “Las capacidades físicas”, the fatigue is calculated in base of the value of constitution and core exxet P11 “tabla 2: bonos de característica” the constitution can be at maximum 20, also if you have the advantage of “infatigable” in core exxet P20  you could add 9 point of fatigue and if you can choose the race “Jayán” in core exxet P30 which add 1 additional point of fatigue the total is 30 .

**Steps**

1. Click in the button "crear nuevo personaje" in the left panel in the superior mid
2. In the section "detalles" fill the field "cansancio" with a value above the maximum (31)
3. Click the "guardar" button

**Expected Output**

- Successfully add the character to the characters list
- The maximum value of field "cansancio" should be limited to 30

**Real Output**
[AMT-CNC-6.png](https://drive.google.com/file/d/1dj6N--g3HOkRAFnYtPkh972Q3xHHhJWH/view?usp=drive_link)

**Comment by aoalejo** [comment]
it's limited now to 9999, I know it's not the expected answer, but I prefer not to limit more the creation, because it can be a monster or anything that has 100 points of fatigue per example.
