### ISSUE TITLE
Searching NPC’s by “Lv. #” doesn’t list anything

### ISSUE THREAD

**Issue by Balaturdar** [aoalejo/animaMasterToolkit#9]
O.S | Windows 11
Browser | Mozilla Firefox 121.0.1 (64-bit)

**Description**
When you search NPC’s by their level this shows results only if it’s a number, this can be counterintuitive and the user may not know how to use it.

**Steps**

1. Click the icon with 2 persons at the top right
2. Click the search bar
3. Write the level of the NPC (“Lv. 3”, “lv. 2” or “lvl 4” )

**Expected Output**
A list of NPC with that level 

**Real Output**
[AMT-S-3a.png](https://drive.google.com/file/d/1lR2rcmVbJBBmAaKhKEUa86T62-X_VCu4/view?usp=drive_link) [AMT-S-3b.png](https://drive.google.com/file/d/1V9kefEIs-ltsL70UGxWkL-OBmFaEEGcn/view?usp=drive_link)

**Comment by aoalejo** [comment]
fixed on: https://github.com/aoalejo/animaMasterToolkit/pull/34
